swagger: '2.0'
info:
  version: 0.0.2
  title: Servicio para consultar los datos del presupuesto
  description: Servicio para consultar los los datos del presupuesto
host: 10.51.251.159:9004
basePath: /WSBAZCREDCDT
schemes:
  - https
produces:
  - application/json
paths:
  /WSCargaClienteSurtimiento/cargaDetallePresupuesto:
    post:
      description: Servicio para consultar los datos del presupuesto
      tags:
        - Servicio para consultar los datos del presupuesto
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: Parámetros de entrada.
          description: Información de entrada.
          required: true
          schema:
            $ref: '#/definitions/WSCargaClienteSurtimientoRequest'
      responses:
        200:
          description: Operación exitosa
          schema:
            $ref: '#/definitions/WSCargaClienteSurtimientoResponse'
          examples:
            application/json: |-
              {
                "codigo": "200.WSCargaClienteSurtimiento",
                "mensaje": "Se cargaron los datos del cliente Correctamente -- ",
                "folio": "200",
                "resultado": {
                  "datosPreparametricoLista": null,
                  "datosPreparametrico": {
                    "folioPreparametrico": "170322",
                    "negocioID": "1",
                    "numeroTienda": "832",
                    "clienteID": "126816",
                    "digitoVerificador": "2",
                    "tipoVenta": "2",
                    "numeroEmpleado": "117   ",
                    "numeroPlazo": "48",
                    "periodo": "1",
                    "pagoAbonoNormal": "428.00",
                    "pagoUltimoAbono": "430.00",
                    "fechaPresupuesto": "30/01/2020 01:10:00 p. m."
                  },
                  "datosDetallePreparametricoLista": [
                    {
                      "FolioParametrico": "170322",
                      "productoSkuBAZ": "741669",
                      "precioProducto": "7000.00",
                      "cantidadProducto": "1",
                      "descuentoProducto": "0.00",
                      "descuentoEspecial": "0.00",
                      "sobreprecio": "2000.0000",
                      "porcentajeIVA": "0.16",
                      "descuentoMarket": "0.00",
                      "costoProducto": "7000.00",
                      "statusPresupuesto": "1",
                      "interesesProducto": "2000.00",
                      "engancheProducto": "1000.00",
                      "clavePromProducto": "1",
                      "comisionV": "0.00",
                      "comisionG": "0.00"
                    }
                  ],
                  "detalleProntoPago": {
                    "folioPreparametrico": "170322",
                    "fechaPromocion": "30/01/2020 01:10:00 p. m.",
                    "abonoPuntual": "364.00",
                    "porcentajeDescuento": "20.00",
                    "statusPromocion": "3",
                    "numeroDePedido": ""
                  },
                  "detalleLigaClienteLCR": {
                    "folioPresupuestoLCR": "170322",
                    "fiPaisCteU": "1",
                    "fiCanalCteU": "17",
                    "fiSucursalCteU": "832",
                    "fiFolioCteU": "57",
                    "fiNgcioIdEktGest": "1",
                    "fiNoTiendaGest": "2244",
                    "fiCteIdGest": "322492",
                    "fiDigitoVerGest": "8",
                    "fiNgcioIdEkt": "1",
                    "fiNoTiendaEkt": "832",
                    "fiCteIdEkt": "126816",
                    "fiDigitoVerEkt": "2",
                    "fcTarjeta": "",
                    "fcHuella1": "6",
                    "fcHuella2": "6",
                    "fcHuella3": "6",
                    "fcHuella4": "6",
                    "fcHuella5": "6",
                    "Nombre": "MARIA FLORENCIAS MORENOS",
                    "EstaConxion": "0",
                    "finocomprascredito": "0",
                    "fiDomiciliacion": "",
                    "fiPaisAdicional": "",
                    "fiCanalAdicional": "",
                    "fiSucursalAdicional": "",
                    "fiFolioAdicional": "",
                    "fcTarjetaAdicional": ""
                  }
                }
              }
        400:
          description: Error cuando no recibe un content type válido
          schema:
            $ref: '#/definitions/error'
          examples:
            application/json: |-
              {
                "codigo": "400.WSCargaClienteSurtimiento",
                "mensaje": "Solicitud incorrecta",
                "folio": "Co-201909250626217206",
                "info": "https://baz-developer.bancoazteca.com.mx/errors#400.CobranzaCredito-CotizadorConsumoTel.104400",
                "detalles": [
                  ""
                ]
              }
        404:
          description: Error cuando se realiza una solicitud a un recurso que no está definido
          schema:
            $ref: '#/definitions/error'
          examples:
            application/json: |-
              {
                "codigo": "404.WSCargaClienteSurtimiento",
                "mensaje": "Recurso no encontrado",
                "folio": "Co-201909061905470600",
                "info": "https://baz-developer.bancoazteca.com.mx/errors#404.CobranzaCredito-CotizadorConsumoTel.104404",
                "detalles": [
                  ""
                ]
              }
        500:
          description: Error interno en el servidor.
          schema:
            $ref: '#/definitions/error'
          examples:
            application/json: |-
               {
                  "codigo": "500.WSCargaClienteSurtimiento",
                  "mensaje": "Error inesperado en la aplicación",
                  "folio": "Co-201909061515470600",
                  "info": "https://baz-developer.bancoazteca.com.mx/errors#500.CobranzaCredito-CotizadorConsumoTel.104500",
                  "detalles": [
                    ""
                  ]
                }
definitions:
    WSCargaClienteSurtimientoRequest:
     type: object
     properties:
      folioPreparametrico:
        type: string
        description: folioPreparametrico
        example: 170267
      sucursalGestora:
          type: string
          description: sucursalGestora
          example: 832
    WSCargaClienteSurtimientoResponse:
     type: object
     properties:
      codigo:
        type: string
        description: Código operación
        example: 200.CobranzaCredito-CotizadorConsumoTel.104200
      mensaje:
        type: string
        description: Descripción de la operación
        example: Operación exitosa
      folio:
        type: string
        description: Folio de la operación
        example: Co-201909061024408700
    error:
     type: object
     properties:
      codigo:
        type: string
        description: Código del error.
      mensaje:
        type: string
        description: Descripción del error.
      folio: 
        type: string
        description: Número de folio de la operación.
      info:
        type: string
        description: Rutas de ayuda para atender el error.
      detalles:
        type: array
        items:
          type: string